[package]
name = "mother-brain-discord-bot"
version = "0.1.0"
edition = "2021"
authors = ["Bolu <bolu@tuta.io>"]
repository = "https://codeberg.org/bolu/mother-brain"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
openssl = "0.10.63"
serenity = { default-features = false, version = "0.12.0", features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
    "builder"
] }
rand = "0.9.1"
rand_chacha = "0.9.0"
rs_sha512 = "0.1.3"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
